apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ftyd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ftyd
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ftyd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ftyd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ftyd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qjnp-tenant/rhtap-demo-app/hacbs-test-project-ftyd@sha256:398270bb0e9aea5ef0a4119e67529fccad857b6ae16aab89dd1579e94894d6e5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
